[profile.default]
src = 'contracts'
out = 'out'
test = 'tests'
libs = ['lib']

remappings = [
  '@contracts=contracts',
  '@test=test',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]